apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/dentalassistai/backend-hw:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
